-- ============================================
-- OPTIMAL BREAKS — Seed Data
-- Run after 001_initial_schema.sql
-- ============================================

-- =============================================
-- ARTISTS (12 initial)
-- =============================================
INSERT INTO public.artists (slug, name, name_display, country, bio_en, bio_es, category, styles, era, essential_tracks, is_featured, sort_order) VALUES
('the-prodigy', 'The Prodigy', 'THE PRODIGY', 'UK', 'Liam Howlett and crew redefined live electronic music. From rave to punk to global phenomenon. Aggressive, wild and absolutely iconic.', 'Liam Howlett y crew redefinieron la electrónica en directo. Del rave al punk al fenómeno global. Agresivos, salvajes y absolutamente icónicos.', 'uk_legend', ARRAY['Big Beat', 'Rave', 'Punk Electronic'], '1990s', ARRAY['Firestarter', 'Breathe', 'Smack My Bitch Up', 'Out of Space', 'Voodoo People'], true, 1),

('fatboy-slim', 'Fatboy Slim', 'FATBOY SLIM', 'UK', 'Norman Cook turned breaks into a planetary party. From Brighton Beach to stadiums worldwide. Anthems that define entire festivals.', 'Norman Cook convirtió los breaks en fiesta planetaria. De Brighton Beach a estadios de todo el mundo. Himnos que definen festivales enteros.', 'uk_legend', ARRAY['Big Beat', 'Funk', 'House'], '1990s', ARRAY['Right Here Right Now', 'Praise You', 'The Rockafeller Skank', 'Weapon of Choice'], true, 2),

('chemical-brothers', 'The Chemical Brothers', 'THE CHEMICAL BROTHERS', 'UK', 'Tom Rowlands and Ed Simons mixed breaks with psychedelia, rock and electronic experimentation. A sound universe beyond labels.', 'Tom Rowlands y Ed Simons mezclaron breaks con psicodelia, rock y experimentación electrónica. Un universo sonoro sin etiquetas.', 'uk_legend', ARRAY['Big Beat', 'Psychedelic', 'Electronic'], '1990s', ARRAY['Block Rockin Beats', 'Hey Boy Hey Girl', 'Galvanize', 'Star Guitar', 'Setting Sun'], true, 3),

('stanton-warriors', 'Stanton Warriors', 'STANTON WARRIORS', 'UK', 'Dominic Butler and Mark Mayfield. Fat bass, clever samples and devastating sets. Nu skool breaks with its own name. Multiple Breakspoll winners.', 'Dominic Butler y Mark Mayfield. Bass gordo, samples listos y sets devastadores. Nu skool breaks con nombre propio. Múltiples ganadores de Breakspoll.', 'uk_legend', ARRAY['Nu Skool', 'Bass', 'Breaks'], '2000s', ARRAY['Get Up', 'Precinct', 'Turn Me Up', 'The Stomp'], true, 4),

('adam-freeland', 'Adam Freeland', 'ADAM FREELAND', 'UK', 'Marine Parade label founder. Elegance and power combined. Pushed progressive breaks into new territories and global recognition.', 'Fundador del sello Marine Parade. Elegancia y contundencia combinadas. Empujó el progressive breaks hacia nuevos territorios y reconocimiento global.', 'uk_legend', ARRAY['Progressive Breaks', 'Techno'], '2000s', ARRAY['We Want Your Soul', 'Smells Like Breaks Spirit', 'Fear'], true, 5),

('krafty-kuts', 'Krafty Kuts', 'KRAFTY KUTS', 'UK', 'One of the key pioneers in the UK breakbeat and bass movement. The bridge between breaks and hip-hop. Scratching, sampling and flow over broken rhythms. Kept the scene alive through radio, YouTube and constant touring.', 'Uno de los pioneros clave del movimiento breakbeat y bass en UK. El puente entre breaks y hip-hop. Scratching, sampling y flow sobre ritmos rotos. Mantuvo viva la escena a través de radio, YouTube y giras constantes.', 'uk_legend', ARRAY['Breaks', 'Hip-Hop', 'Bass'], '2000s', ARRAY['Gimme the Breaks', 'Feel the Force', 'Shake Them Hips'], true, 6),

('plump-djs', 'Plump DJs', 'PLUMP DJS', 'UK', 'Lee Rous and Andy Gardner. Finger Lickin Records co-founders. Defined the sound of nu skool breaks with heavy bass and party energy.', 'Lee Rous y Andy Gardner. Co-fundadores de Finger Lickin Records. Definieron el sonido del nu skool breaks con bass pesado y energía de fiesta.', 'uk_legend', ARRAY['Nu Skool', 'Breaks', 'Bass'], '2000s', ARRAY['Plump DJs Theme', 'A Plump Night Out', 'Electric Disco'], true, 7),

('lady-waks', 'Lady Waks', 'LADY WAKS', 'Russia', 'DJ, producer, promoter and radio presenter. Best Radio Show and Best DJ at Breakspoll/IBA. Hundreds of episodes of In Da Mix. Kept the global breaks community connected through years of reduced mainstream visibility.', 'DJ, productora, promotora y presentadora de radio. Mejor Radio Show y Mejor DJ en Breakspoll/IBA. Cientos de episodios de In Da Mix. Mantuvo conectada a la comunidad global de breaks durante los años de menor visibilidad.', 'current', ARRAY['Breaks', 'Bass', 'Radio'], '2010s', ARRAY['In Da Mix series'], true, 8),

('freestylers', 'Freestylers', 'FREESTYLERS', 'UK', 'Aston Harvey and Matt Cantor. Early breakbeat pioneers mixing breaks with hip-hop, reggae and MC culture. Brought breakbeat to the mainstream in the late 90s.', 'Aston Harvey y Matt Cantor. Pioneros del breakbeat mezclando breaks con hip-hop, reggae y cultura MC. Llevaron el breakbeat al mainstream a finales de los 90.', 'uk_legend', ARRAY['Breaks', 'Hip-Hop', 'Reggae'], '1990s', ARRAY['B-Boy Stance', 'Push Up', 'Here We Go', 'Ruffneck'], true, 9),

('dj-icey', 'DJ Icey', 'DJ ICEY', 'USA', 'Central figure of the Florida breaks scene. Built the US breaks movement from Orlando with a sound that mixed electro, bass and rave energy.', 'Figura central de la escena Florida breaks. Construyó el movimiento breaks estadounidense desde Orlando con un sonido que mezclaba electro, bass y energía rave.', 'us_artist', ARRAY['Florida Breaks', 'Electro', 'Bass'], '1990s', ARRAY['Escape', 'Generate Power'], true, 10),

('soul-of-man', 'Soul of Man', 'SOUL OF MAN', 'UK', 'Finger Lickin Records founder. Built the label from a tiny office above Bar Vinyl in Camden Town into one of the most important breaks labels in the world.', 'Fundador de Finger Lickin Records. Construyó el sello desde una oficina diminuta encima de Bar Vinyl en Camden Town hasta convertirlo en uno de los sellos de breaks más importantes del mundo.', 'uk_legend', ARRAY['Breaks', 'Funk', 'Bass'], '2000s', ARRAY['Steppin Out', 'The Stomp'], true, 11),

('deekline', 'Deekline', 'DEEKLINE', 'UK', 'Prolific producer and DJ straddling breaks, jungle, bass and garage. Collaborated extensively with Ed Solo. Kept producing and releasing through the quiet years.', 'Prolífico productor y DJ entre breaks, jungle, bass y garage. Colaboró extensamente con Ed Solo. Siguió produciendo y publicando durante los años silenciosos.', 'current', ARRAY['Breaks', 'Jungle', 'Bass'], '2000s', ARRAY['I Don''t Smoke', 'Bouncing', 'No No No'], true, 12);

-- =============================================
-- LABELS (8 initial)
-- =============================================
INSERT INTO public.labels (slug, name, country, founded_year, description_en, description_es, key_artists, key_releases, is_active, is_featured) VALUES
('finger-lickin', 'Finger Lickin'' Records', 'UK', 1996, 'Founded by Soul of Man from a tiny office above Bar Vinyl in Camden Town. Won Best Label at Breakspoll 2003. One of the most important breakbeat labels ever, defining the nu skool sound.', 'Fundado por Soul of Man desde una oficina diminuta encima de Bar Vinyl en Camden Town. Ganó Mejor Sello en Breakspoll 2003. Uno de los sellos de breakbeat más importantes de la historia, definiendo el sonido nu skool.', ARRAY['Plump DJs', 'Soul of Man', 'Freestylers'], ARRAY['Plump DJs - Plump Night Out', 'Various - Finger Lickin Good'], true, true),

('botchit-scarper', 'Botchit & Scarper', 'UK', 1997, 'London-based label that championed the heavier, darker side of breakbeat. Released key tracks that pushed the genre boundaries.', 'Sello londinense que defendió el lado más pesado y oscuro del breakbeat. Publicó tracks clave que empujaron los límites del género.', ARRAY['Freq Nasty', 'Atomic Hooligan'], ARRAY['Various - Botchit Breaks'], false, true),

('marine-parade', 'Marine Parade', 'UK', 2000, 'Adam Freeland''s label. Defined the progressive breaks sound with elegance and dancefloor power. Named after the Brighton seafront road.', 'El sello de Adam Freeland. Definió el sonido del progressive breaks con elegancia y potencia de pista. Nombrado por la carretera del paseo marítimo de Brighton.', ARRAY['Adam Freeland', 'Rennie Pilgrem'], ARRAY['Adam Freeland - We Want Your Soul'], false, true),

('skint-records', 'Skint Records', 'UK', 1995, 'Brighton-based label, home to Fatboy Slim. Central to the big beat explosion of the late 90s. Released some of the biggest breakbeat records in history.', 'Sello de Brighton, casa de Fatboy Slim. Central en la explosión del big beat de finales de los 90. Publicó algunos de los discos de breakbeat más grandes de la historia.', ARRAY['Fatboy Slim', 'Midfield General', 'Lo-Fi Allstars'], ARRAY['Fatboy Slim - You''ve Come a Long Way Baby'], true, true),

('tcr', 'TCR', 'UK', 2001, 'Stanton Warriors'' label. Released some of the heaviest nu skool breaks tracks. Consistent output of dancefloor-ready breaks.', 'El sello de Stanton Warriors. Publicó algunos de los tracks de nu skool breaks más pesados. Producción constante de breaks listos para la pista.', ARRAY['Stanton Warriors', 'Dub Pistols'], ARRAY['Stanton Warriors - The Stanton Warriors'], true, true),

('passenger', 'Passenger Records', 'UK', 2002, 'Quality breaks label that contributed to the nu skool era with carefully curated releases.', 'Sello de breaks de calidad que contribuyó a la era nu skool con lanzamientos cuidadosamente curados.', ARRAY['Various'], ARRAY[], false, false),

('mob-records', 'Mob Records', 'UK', 1999, 'Independent breakbeat label operating from London. Part of the underground breaks network of the early 2000s.', 'Sello independiente de breakbeat operando desde Londres. Parte de la red underground de breaks de principios de los 2000.', ARRAY['Various'], ARRAY[], false, false),

('breakbeat-kaos', 'Breakbeat Kaos', 'UK', 2003, 'DJ Fresh and Adam F''s label. Bridged breakbeat and drum and bass with high-energy releases.', 'El sello de DJ Fresh y Adam F. Tendió un puente entre el breakbeat y el drum and bass con lanzamientos de alta energía.', ARRAY['DJ Fresh', 'Adam F'], ARRAY['DJ Fresh - Gold Dust'], true, true);

-- =============================================
-- EVENTS (6 initial)
-- =============================================
INSERT INTO public.events (slug, name, description_en, description_es, event_type, date_start, location, city, country, venue, lineup, is_featured) VALUES
('breakspoll-awards', 'Breakspoll International Breakbeat Awards', 'The international breakbeat awards ceremony. Held at Fabric London from 2003, later at Cable, Fire and Sound Control Manchester. The most prestigious recognition in breakbeat culture.', 'La ceremonia internacional de premios del breakbeat. Celebrada en Fabric Londres desde 2003, después en Cable, Fire y Sound Control Manchester. El reconocimiento más prestigioso de la cultura breakbeat.', 'past_iconic', '2003-01-01', 'Various venues', 'London', 'UK', 'Fabric / Cable / Fire', ARRAY['Stanton Warriors', 'Plump DJs', 'Krafty Kuts', 'Adam Freeland', 'Lady Waks'], true),

('breakfest-perth', 'Breakfest', 'Annual breakbeat, drum and bass, hip hop and electronic music festival in Perth, Australia. Active from 2001 to 2022 with a special return in 2025. One of the longest-running breaks festivals worldwide.', 'Festival anual de breakbeat, drum and bass, hip hop y música electrónica en Perth, Australia. Activo de 2001 a 2022 con regreso especial en 2025. Uno de los festivales de breaks más longevos del mundo.', 'past_iconic', '2001-01-01', 'Various venues', 'Perth', 'Australia', NULL, ARRAY['Various international and local DJs'], true),

('martin-carpena-2002', 'Martín Carpena Breakbeat Event', 'The March 2nd 2002 event at Palacio de Deportes Martín Carpena, Málaga. Over 14,000 people inside and thousands more outside. A tragic turning point: two deaths led to the stigmatization and decline of the Andalusian breakbeat scene.', 'El evento del 2 de marzo de 2002 en el Palacio de Deportes Martín Carpena, Málaga. Más de 14.000 personas dentro y miles más fuera. Un punto de inflexión trágico: dos muertes llevaron a la estigmatización y declive de la escena breakbeat andaluza.', 'past_iconic', '2002-03-02', 'Palacio de Deportes Martín Carpena', 'Málaga', 'Spain', 'Martín Carpena', ARRAY[], true),

('breakpoint-festival', 'Breakpoint Festival', 'New breakbeat and bass music festival bringing together classic and new-generation breaks artists.', 'Nuevo festival de breakbeat y bass music que reúne artistas de breaks clásicos y nueva generación.', 'upcoming', '2026-04-12', 'Warehouse BCN', 'Barcelona', 'Spain', 'Warehouse BCN', ARRAY['TBA'], true),

('nu-breaks-sessions', 'Nu Breaks Sessions', 'Monthly club night dedicated to breakbeat, breaks and UK bass at Fabric London.', 'Sesión mensual de club dedicada al breakbeat, breaks y UK bass en Fabric Londres.', 'club_night', '2026-05-23', 'Fabric', 'London', 'UK', 'Fabric', ARRAY['Stanton Warriors', 'Krafty Kuts'], true),

('optimal-breaks-showcase', 'Optimal Breaks Showcase', 'Launch event for the Optimal Breaks project. Local and international breaks DJs in Murcia.', 'Evento de lanzamiento del proyecto Optimal Breaks. DJs de breaks locales e internacionales en Murcia.', 'upcoming', '2026-09-08', 'Sala B', 'Murcia', 'Spain', 'Sala B', ARRAY['TBA'], true);

-- =============================================
-- SCENES (6 initial)
-- =============================================
INSERT INTO public.scenes (slug, name_en, name_es, country, region, description_en, description_es, key_artists, key_labels, key_venues, era, is_featured) VALUES
('uk-breakbeat', 'UK Breakbeat', 'Breakbeat Británico', 'UK', 'London, Manchester, Bristol', 'The birthplace of modern breakbeat culture. UK took acid house, techno, hip-hop and Jamaican soundsystem culture and fused them into rave, breakbeat hardcore, jungle and the nu skool breaks movement. Fabric, pirate radio stations and record shops like those in Camden were the infrastructure.', 'La cuna de la cultura breakbeat moderna. UK cogió el acid house, el techno, el hip-hop y la cultura soundsystem jamaicana y los fusionó en rave, breakbeat hardcore, jungle y el movimiento nu skool breaks. Fabric, emisoras de radio pirata y tiendas de discos como las de Camden fueron la infraestructura.', ARRAY['The Prodigy', 'Chemical Brothers', 'Fatboy Slim', 'Stanton Warriors', 'Plump DJs'], ARRAY['Finger Lickin', 'Skint', 'Marine Parade', 'TCR', 'Botchit & Scarper'], ARRAY['Fabric', 'The End', 'Bar Vinyl Camden', 'Ministry of Sound'], '1988 — present', true),

('us-breaks', 'US Breaks', 'Breaks Americano', 'USA', 'Florida, California', 'While house and techno dominated the US club narrative, breaks carved out regional strongholds. The Florida breaks scene, led from Orlando, mixed electro, bass and rave energy. West Coast funky breaks added another dimension.', 'Mientras el house y el techno dominaban la narrativa del club estadounidense, los breaks se hicieron fuertes regionalmente. La escena Florida breaks, liderada desde Orlando, mezclaba electro, bass y energía rave. Los funky breaks de la costa oeste añadieron otra dimensión.', ARRAY['DJ Icey', 'Crystal Method', 'Freq Nasty'], ARRAY[], ARRAY[], '1990 — present', true),

('andalusian-breakbeat', 'Andalusian Breakbeat', 'Breakbeat Andaluz', 'Spain', 'Seville, Málaga, Cádiz', 'An exceptional case in European breakbeat history. Between 1992 and 2002, breakbeat achieved unprecedented popularity in Andalusia, becoming a mass youth culture phenomenon. The Martín Carpena tragedy of 2002 marked its decline. Documented in the film Break Nation (2023).', 'Un caso excepcional en la historia del breakbeat europeo. Entre 1992 y 2002, el breakbeat alcanzó una popularidad sin precedentes en Andalucía, convirtiéndose en un fenómeno de cultura juvenil de masas. La tragedia del Martín Carpena de 2002 marcó su declive. Documentado en la película Break Nation (2023).', ARRAY[], ARRAY[], ARRAY['Martín Carpena', 'Canal Sur Radio'], '1992 — 2002', true),

('australian-breaks', 'Australian Breaks', 'Breaks Australiano', 'Australia', 'Perth, Melbourne, Sydney', 'A solid and persistent scene. Perth hosted Breakfest, one of the longest-running breaks festivals worldwide (2001-2022). Pendulum formed there before moving to London. Not as culturally central as Andalusia but consistent and real.', 'Una escena sólida y persistente. Perth acogió Breakfest, uno de los festivales de breaks más longevos del mundo (2001-2022). Pendulum se formó allí antes de mudarse a Londres. No tan culturalmente central como Andalucía pero consistente y real.', ARRAY['Pendulum'], ARRAY[], ARRAY['Breakfest Perth'], '2001 — present', true),

('russian-eastern-europe', 'Russian & Eastern European Breaks', 'Breaks Ruso y de Europa del Este', 'Russia', 'Moscow, St. Petersburg', 'A significant breaks scene developed in Russia and Eastern Europe, particularly through radio shows, online communities and dedicated festivals. Lady Waks became one of the most important figures keeping global breaks connected.', 'Una escena de breaks significativa se desarrolló en Rusia y Europa del Este, particularmente a través de programas de radio, comunidades online y festivales dedicados. Lady Waks se convirtió en una de las figuras más importantes manteniendo conectados los breaks globales.', ARRAY['Lady Waks', 'Beatman & Ludmilla'], ARRAY[], ARRAY[], '2005 — present', true),

('latin-america-breaks', 'Latin American Breaks', 'Breaks Latinoamericano', 'Various', 'Mexico, Colombia, Argentina', 'An emerging and growing scene with producers and DJs adopting breaks and UK bass sounds. Digital platforms enabled connection with the global breaks community without requiring the physical infrastructure of earlier eras.', 'Una escena emergente y en crecimiento con productores y DJs adoptando sonidos de breaks y UK bass. Las plataformas digitales permitieron la conexión con la comunidad global de breaks sin necesitar la infraestructura física de eras anteriores.', ARRAY[], ARRAY[], ARRAY[], '2010 — present', false);

-- =============================================
-- BLOG POSTS (3 initial)
-- =============================================
INSERT INTO public.blog_posts (slug, title_en, title_es, excerpt_en, excerpt_es, content_en, content_es, category, tags, author, is_published, is_featured) VALUES
('the-amen-break', 'The Amen Break: 6 Seconds That Changed Music Forever', 'El Amen Break: 6 Segundos Que Cambiaron la Música Para Siempre', 'How a six-second drum break from a 1969 soul track became the most sampled loop in history.', 'Cómo un break de batería de seis segundos de un tema soul de 1969 se convirtió en el loop más sampleado de la historia.', '<h2>The Source</h2><p>In 1969, The Winstons recorded "Amen, Brother" as the B-side to their single "Color Him Father." Drummer Gregory C. Coleman played a six-second drum solo that would become the foundation of entire genres.</p><h2>The Discovery</h2><p>In the mid-1980s, hip-hop producers began isolating and looping this break. By the early 1990s, the Amen break had become central to jungle and drum and bass production in the UK.</p><h2>The Legacy</h2><p>Today, the Amen break is considered the most sampled piece of music in history. It appears in thousands of tracks across hip-hop, jungle, drum and bass, breakbeat, and electronic music. Yet Gregory Coleman died homeless in 2006, having never received royalties for his contribution.</p>', '<h2>El Origen</h2><p>En 1969, The Winstons grabaron "Amen, Brother" como cara B de su single "Color Him Father." El batería Gregory C. Coleman tocó un solo de batería de seis segundos que se convertiría en la base de géneros enteros.</p><h2>El Descubrimiento</h2><p>A mediados de los 80, los productores de hip-hop empezaron a aislar y repetir este break. A principios de los 90, el Amen break se había convertido en central para la producción de jungle y drum and bass en UK.</p><h2>El Legado</h2><p>Hoy, el Amen break se considera la pieza musical más sampleada de la historia. Aparece en miles de tracks de hip-hop, jungle, drum and bass, breakbeat y música electrónica. Sin embargo, Gregory Coleman murió sin hogar en 2006, sin haber recibido nunca royalties por su contribución.</p>', 'retrospective', ARRAY['amen break', 'history', 'sampling', 'jungle', 'drum and bass'], 'Optimal Breaks', true, true),

('break-nation-documentary', 'Break Nation: The Documentary Andalusia Needed', 'Break Nation: El Documental Que Andalucía Necesitaba', 'A review of David Pareja''s 2023 documentary about the rise and fall of breakbeat in southern Spain.', 'Una reseña del documental de David Pareja de 2023 sobre el auge y caída del breakbeat en el sur de España.', '<h2>The Story</h2><p>Break Nation (2023), directed by David Pareja, traces the explosive growth of breakbeat in Andalusia between 1992 and 2002. It covers the parties, the radio shows, the DJs, the culture — and the tragic events at Martín Carpena in Málaga that marked the end of the golden era.</p><h2>Why It Matters</h2><p>This documentary fills a crucial gap in breakbeat history. While the UK scene has been extensively documented, the Andalusian phenomenon — where breakbeat achieved mass popularity beyond anything seen in the rest of Europe — had never been properly told on film.</p>', '<h2>La Historia</h2><p>Break Nation (2023), dirigido por David Pareja, recorre el crecimiento explosivo del breakbeat en Andalucía entre 1992 y 2002. Cubre las fiestas, los programas de radio, los DJs, la cultura — y los trágicos eventos del Martín Carpena de Málaga que marcaron el fin de la era dorada.</p><h2>Por Qué Importa</h2><p>Este documental llena un vacío crucial en la historia del breakbeat. Mientras la escena británica ha sido ampliamente documentada, el fenómeno andaluz — donde el breakbeat alcanzó una popularidad de masas que superó todo lo visto en el resto de Europa — nunca se había contado bien en cine.</p>', 'review', ARRAY['documentary', 'andalusia', 'break nation', 'spain'], 'Optimal Breaks', true, true),

('who-kept-breakbeat-alive', 'Who Kept Breakbeat Alive?', '¿Quién Mantuvo Vivo el Breakbeat?', 'During the quiet years, some DJs and producers refused to let the genre disappear. This is their story.', 'Durante los años silenciosos, algunos DJs y productores se negaron a dejar morir el género. Esta es su historia.', '<h2>The Quiet Years</h2><p>After the mid-2000s, breakbeat lost its central position in club culture. But it never disappeared. A network of dedicated DJs, radio hosts, YouTube channels and small labels kept the flame alive.</p><h2>The Regulars</h2><p>Krafty Kuts maintained a constant presence with mixes, sets and YouTube sessions. Lady Waks produced hundreds of episodes of her In Da Mix radio show. Stanton Warriors kept touring and releasing. These artists didn''t wait for a revival — they were the reason one was possible.</p><h2>The Digital Bridge</h2><p>Beatport maintained a dedicated Breaks / Breakbeat / UK Bass category throughout these years. SoundCloud and Mixcloud became archives. YouTube became a discovery platform. The genre survived more as active culture than as a dominant market.</p>', '<h2>Los Años Silenciosos</h2><p>Después de mediados de los 2000, el breakbeat perdió su posición central en la cultura de club. Pero nunca desapareció. Una red de DJs dedicados, presentadores de radio, canales de YouTube y sellos pequeños mantuvieron viva la llama.</p><h2>Los Habituales</h2><p>Krafty Kuts mantuvo una presencia constante con mixes, sets y sesiones en YouTube. Lady Waks produjo cientos de episodios de su programa de radio In Da Mix. Stanton Warriors siguieron de gira y publicando. Estos artistas no esperaron a un revival — fueron la razón de que fuera posible.</p><h2>El Puente Digital</h2><p>Beatport mantuvo una categoría dedicada de Breaks / Breakbeat / UK Bass durante todos estos años. SoundCloud y Mixcloud se convirtieron en archivos. YouTube se convirtió en plataforma de descubrimiento. El género sobrevivió más como cultura activa que como mercado dominante.</p>', 'article', ARRAY['history', 'DJs', 'radio', 'youtube', 'beatport'], 'Optimal Breaks', true, true);

-- =============================================
-- MIXES (6 initial)
-- =============================================
INSERT INTO public.mixes (slug, title, artist_name, description_en, description_es, mix_type, year, duration_minutes, platform, is_featured) VALUES
('krafty-kuts-golden-era', 'Krafty Kuts — Golden Era Breaks Mix', 'Krafty Kuts', 'A journey through the golden era of breakbeat. Classic cuts, rare grooves and floor fillers.', 'Un viaje por la era dorada del breakbeat. Cortes clásicos, grooves raros y reventapistas.', 'youtube_session', 2023, 62, 'youtube', true),
('lady-waks-in-da-mix-500', 'Lady Waks — In Da Mix #500', 'Lady Waks', 'The 500th episode of the legendary breaks radio show. A milestone in breakbeat broadcasting.', 'El episodio 500 del legendario programa de radio de breaks. Un hito en la emisión de breakbeat.', 'radio_show', 2024, 58, 'mixcloud', true),
('stanton-warriors-fabric', 'Stanton Warriors — Live at Fabric', 'Stanton Warriors', 'Recorded live at Fabric London. One of the defining breakbeat live sets of the 2000s.', 'Grabado en directo en Fabric Londres. Uno de los sets de breakbeat en directo definitorios de los 2000.', 'classic_set', 2005, 74, 'soundcloud', true),
('adam-freeland-essential-mix', 'Adam Freeland — Essential Mix BBC', 'Adam Freeland', 'Adam Freeland''s Essential Mix for BBC Radio 1. Progressive breaks at its absolute finest.', 'El Essential Mix de Adam Freeland para BBC Radio 1. Progressive breaks en su máxima expresión.', 'essential_mix', 2003, 120, 'youtube', true),
('plump-djs-beats-working', 'Plump DJs — Beats Working Vol.1', 'Plump DJs', 'Classic Plump DJs podcast mix. Pure nu skool breaks energy from the Finger Lickin crew.', 'Mix de podcast clásico de Plump DJs. Pura energía nu skool breaks del crew de Finger Lickin.', 'podcast', 2008, 65, 'soundcloud', true),
('deekline-jungle-cakes', 'Deekline & Ed Solo — Jungle Cakes Mix', 'Deekline', 'Breaks meets jungle. The crossover sound that Deekline and Ed Solo perfected over years of collaboration.', 'Breaks meets jungle. El sonido crossover que Deekline y Ed Solo perfeccionaron durante años de colaboración.', 'youtube_session', 2020, 55, 'youtube', true);

-- =============================================
-- HISTORY ENTRIES (7 initial)
-- =============================================
INSERT INTO public.history_entries (slug, title_en, title_es, content_en, content_es, section, year_start, year_end, sort_order) VALUES
('origins', 'The Origins of the Break', 'Los Orígenes del Break', 'In 1973, DJ Kool Herc in the Bronx pioneered the technique of extending drum breaks from funk and soul records using two copies of the same vinyl. Those seconds of pure percussion became the seed of hip-hop and electronic breakbeat. James Brown, The Winstons, and The Incredible Bongo Band provided the raw material that would fuel decades of music.', 'En 1973, DJ Kool Herc en el Bronx fue pionero en la técnica de extender los breaks de batería de discos de funk y soul usando dos copias del mismo vinilo. Esos segundos de percusión pura se convirtieron en la semilla del hip-hop y del breakbeat electrónico. James Brown, The Winstons y The Incredible Bongo Band proporcionaron la materia prima que alimentaría décadas de música.', 'origins', 1970, 1984, 1),
('uk-rave', 'UK Rave Culture and Breakbeat Hardcore', 'Cultura Rave UK y Breakbeat Hardcore', 'When acid house and techno reached the UK in the late 1980s, the British didn''t just copy it — they broke it, mixed it with hip-hop, Jamaican soundsystem culture and pirate radio, and created breakbeat hardcore and the early rave scene. Illegal warehouses, fields and motorways became the backdrop for a cultural revolution.', 'Cuando el acid house y el techno llegaron a UK a finales de los 80, los británicos no se limitaron a copiarlo — lo rompieron, lo mezclaron con hip-hop, cultura soundsystem jamaicana y radio pirata, y crearon el breakbeat hardcore y la escena rave temprana. Warehouses ilegales, campos y autopistas se convirtieron en el escenario de una revolución cultural.', 'uk_breakbeat', 1988, 1994, 2),
('big-beat-era', 'The Big Beat Explosion', 'La Explosión del Big Beat', 'The Prodigy, Chemical Brothers, Fatboy Slim. In the mid-to-late 1990s, breaks filled stadiums, MTV and charts worldwide. Big beat took the energy of breakbeat and made it accessible to millions. This was the commercial peak of broken-beat electronic music.', 'The Prodigy, Chemical Brothers, Fatboy Slim. A mediados-finales de los 90, los breaks llenaron estadios, MTV y las listas de todo el mundo. El big beat cogió la energía del breakbeat y la hizo accesible a millones. Este fue el pico comercial de la música electrónica de ritmo roto.', 'uk_breakbeat', 1995, 2000, 3),
('nu-skool', 'The Nu Skool Breaks Era', 'La Era del Nu Skool Breaks', 'Stanton Warriors, Plump DJs, Adam Freeland, Krafty Kuts. The break got polished: cleaner production, fatter bass, built to destroy dancefloors. Breakspoll awards, Fabric residencies, and labels like Finger Lickin'' and Marine Parade defined the scene.', 'Stanton Warriors, Plump DJs, Adam Freeland, Krafty Kuts. El break se pulió: producción más limpia, bass más gordo, construido para reventar pistas. Premios Breakspoll, residencias en Fabric y sellos como Finger Lickin'' y Marine Parade definieron la escena.', 'uk_breakbeat', 2000, 2006, 4),
('andalusian-golden-age', 'Andalusian Breakbeat: The Golden Age', 'Breakbeat Andaluz: La Edad de Oro', 'Between 1992 and 2002, breakbeat achieved unprecedented popularity in Andalusia. Canal Sur Radio, massive events, and a youth culture that embraced breaks as its own created a phenomenon considered unique in southern Europe. The Martín Carpena tragedy of March 2002 in Málaga — with two deaths — marked the end of this era and the stigmatization of the scene.', 'Entre 1992 y 2002, el breakbeat alcanzó una popularidad sin precedentes en Andalucía. Canal Sur Radio, eventos masivos y una cultura juvenil que abrazó los breaks como propios crearon un fenómeno considerado único en el sur de Europa. La tragedia del Martín Carpena en marzo de 2002 en Málaga — con dos muertes — marcó el fin de esta era y la estigmatización de la escena.', 'andalusian', 1992, 2002, 5),
('decline-and-latency', 'The Decline: From Centre Stage to Latency', 'El Declive: Del Centro a la Latencia', 'After the mid-2000s, breakbeat lost mainstream centrality globally. In the UK, Breakspoll moved from Fabric to smaller venues. Many producers shifted to electro-house, dubstep or drum and bass. In Andalusia, the decline was accelerated by the Martín Carpena fallout. But the genre never died — it went latent. DJs like Krafty Kuts and Lady Waks kept the flame alive through radio, YouTube and constant touring.', 'Después de mediados de los 2000, el breakbeat perdió centralidad mainstream a nivel global. En UK, Breakspoll se mudó de Fabric a salas más pequeñas. Muchos productores viraron al electro-house, dubstep o drum and bass. En Andalucía, el declive se aceleró por las consecuencias del Martín Carpena. Pero el género nunca murió — quedó latente. DJs como Krafty Kuts y Lady Waks mantuvieron viva la llama a través de radio, YouTube y giras constantes.', 'rise_decline_revival', 2006, 2019, 6),
('digital-era-revival', 'The Digital Era and Resurgence', 'La Era Digital y el Resurgimiento', 'Beatport maintained a dedicated Breaks / Breakbeat / UK Bass category throughout the quiet years. SoundCloud and Mixcloud became archives. YouTube became a discovery platform. New producers emerged, fusing breaks with UK garage, tech house and bass music. The genre survived as active culture and is now experiencing a revival. Break Nation (2023) documented the Andalusian story. The break was never dead — it was just reloading.', 'Beatport mantuvo una categoría dedicada de Breaks / Breakbeat / UK Bass durante los años silenciosos. SoundCloud y Mixcloud se convirtieron en archivos. YouTube se convirtió en plataforma de descubrimiento. Nuevos productores emergieron, fusionando breaks con UK garage, tech house y bass music. El género sobrevivió como cultura activa y ahora experimenta un revival. Break Nation (2023) documentó la historia andaluza. El break nunca estuvo muerto — solo estaba cargando.', 'digital_era', 2020, NULL, 7);
