-- ============================================
-- OPTIMAL BREAKS — Artistas desde cronología /artists (ARTIST_ERAS)
-- Generado por: node scripts/sync-timeline-artists.mjs --sql
-- También puedes poblar sin SQL: npm run db:timeline
-- ============================================

INSERT INTO public.artists (
  slug, name, name_display, country, bio_en, bio_es, category, styles, era,
  essential_tracks, recommended_mixes, related_artists, website, socials,
  is_featured, sort_order, real_name, labels_founded, key_releases, image_url
) VALUES
(
  '808-state',
  '808 State',
  '808 STATE',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1985–1989). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1985–1989). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1985–1989',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  147,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'a-guy-called-gerald',
  'A Guy Called Gerald',
  'A GUY CALLED GERALD',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1985–1989). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1985–1989). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1985–1989',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  148,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'a-skillz',
  'A.Skillz',
  'A.SKILLZ',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2005–2009). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2005–2009). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '2005–2009',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  196,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'acen',
  'Acen',
  'ACEN',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1990–1994). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1990–1994). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1990–1994',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  161,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'afrika-bambaataa',
  'Afrika Bambaataa',
  'AFRIKA BAMBAATAA',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1975–1979). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1975–1979). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1975–1979',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  117,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'afrika-bambaataa-the-soulsonic-force',
  'Afrika Bambaataa & The Soulsonic Force',
  'AFRIKA BAMBAATAA & THE SOULSONIC FORCE',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1980–1984). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1980–1984). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'us_artist',
  ARRAY['Hip Hop', 'Breaks'],
  '1980–1984',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  129,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'ak-sports',
  'AK Sports',
  'AK SPORTS',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2020–2024). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2020–2024). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2020–2024',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  216,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'annie-nightingale',
  'Annie Nightingale',
  'ANNIE NIGHTINGALE',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2000–2004). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2000–2004). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '2000–2004',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  190,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'aquasky',
  'Aquasky',
  'AQUASKY',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2000–2004). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2000–2004). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '2000–2004',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  187,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'art-of-noise',
  'Art of Noise',
  'ART OF NOISE',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1980–1984). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1980–1984). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '1980–1984',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  137,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'atomic-hooligan',
  'Atomic Hooligan',
  'ATOMIC HOOLIGAN',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2000–2004). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2000–2004). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '2000–2004',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  184,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'babe-ruth',
  'Babe Ruth',
  'BABE RUTH',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1970–1974). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1970–1974). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1970–1974',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  111,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'bad-legs',
  'Bad Legs',
  'BAD LEGS',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2020–2024). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2020–2024). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2020–2024',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  212,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'badboe',
  'BadboE',
  'BADBOE',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2010–2014). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2010–2014). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2010–2014',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  201,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'beatman-ludmilla',
  'Beatman & Ludmilla',
  'BEATMAN & LUDMILLA',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2010–2014). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2010–2014). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2010–2014',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  203,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'billy-squier',
  'Billy Squier',
  'BILLY SQUIER',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1970–1974). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1970–1974). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1970–1974',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  112,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'bob-james',
  'Bob James',
  'BOB JAMES',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1975–1979). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1975–1979). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1975–1979',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  121,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'bomb-the-bass',
  'Bomb the Bass',
  'BOMB THE BASS',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1985–1989). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1985–1989). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1985–1989',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  144,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'booker-t-the-m-g-s',
  'Booker T. & the M.G.’s',
  'BOOKER T. & THE M.G.’S',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1970–1974). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1970–1974). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1970–1974',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  110,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'calvertron',
  'Calvertron',
  'CALVERTRON',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2010–2014). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2010–2014). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2010–2014',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  204,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'cameo',
  'Cameo',
  'CAMEO',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1975–1979). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1975–1979). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1975–1979',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  124,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'chic',
  'Chic',
  'CHIC',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1975–1979). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1975–1979). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1975–1979',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  120,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'coldcut',
  'Coldcut',
  'COLDCUT',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1985–1989). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1985–1989). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1985–1989',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  143,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'colombo',
  'Colombo',
  'COLOMBO',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2010–2014). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2010–2014). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2010–2014',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  198,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'curtis-mayfield',
  'Curtis Mayfield',
  'CURTIS MAYFIELD',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1970–1974). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1970–1974). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1970–1974',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  115,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'cut-la-roc',
  'Cut La Roc',
  'CUT LA ROC',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1995–1999). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1995–1999). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1995–1999',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  176,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'de-la-soul',
  'De La Soul',
  'DE LA SOUL',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1985–1989). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1985–1989). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'us_artist',
  ARRAY['Hip Hop', 'Breaks'],
  '1985–1989',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  151,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'deekline-ed-solo',
  'Deekline & Ed Solo',
  'DEEKLINE & ED SOLO',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2005–2009). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2005–2009). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '2005–2009',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  192,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'denham-audio',
  'Denham Audio',
  'DENHAM AUDIO',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2020–2024). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2020–2024). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2020–2024',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  214,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'dennis-coffey',
  'Dennis Coffey',
  'DENNIS COFFEY',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1970–1974). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1970–1974). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1970–1974',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  109,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'dj-cosworth',
  'DJ Cosworth',
  'DJ COSWORTH',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2020–2024). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2020–2024). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2020–2024',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  215,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'dj-fixx',
  'DJ Fixx',
  'DJ FIXX',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2010–2014). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2010–2014). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2010–2014',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  206,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'egyptian-lover',
  'Egyptian Lover',
  'EGYPTIAN LOVER',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1980–1984). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1980–1984). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'us_artist',
  ARRAY['Hip Hop', 'Breaks'],
  '1980–1984',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  134,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'eloquin',
  'Eloquin',
  'ELOQUIN',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2025 →). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2025 →). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2025 →',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  219,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'evil-nine',
  'Evil Nine',
  'EVIL NINE',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2005–2009). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2005–2009). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '2005–2009',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  195,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'far-too-loud',
  'Far Too Loud',
  'FAR TOO LOUD',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2005–2009). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2005–2009). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '2005–2009',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  193,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'fast-eddie',
  'Fast Eddie',
  'FAST EDDIE',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1985–1989). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1985–1989). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'us_artist',
  ARRAY['Hip Hop', 'Breaks'],
  '1985–1989',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  154,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'featurecast',
  'Featurecast',
  'FEATURECAST',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2010–2014). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2010–2014). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2010–2014',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  199,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'foul-play',
  'Foul Play',
  'FOUL PLAY',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1990–1994). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1990–1994). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1990–1994',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  166,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'freq-nasty',
  'Freq Nasty',
  'FREQ NASTY',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2005–2009). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2005–2009). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '2005–2009',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  194,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'funkadelic',
  'Funkadelic',
  'FUNKADELIC',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1975–1979). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1975–1979). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1975–1979',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  123,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'grandmaster-flash',
  'Grandmaster Flash',
  'GRANDMASTER FLASH',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1975–1979). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1975–1979). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1975–1979',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  116,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'grandmaster-flash-the-furious-five',
  'Grandmaster Flash & The Furious Five',
  'GRANDMASTER FLASH & THE FURIOUS FIVE',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1980–1984). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1980–1984). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'us_artist',
  ARRAY['Hip Hop', 'Breaks'],
  '1980–1984',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  128,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'grandmaster-flowers',
  'Grandmaster Flowers',
  'GRANDMASTER FLOWERS',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1975–1979). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1975–1979). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1975–1979',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  118,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'guau',
  'Guau',
  'GUAU',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2015–2019). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2015–2019). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2015–2019',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  207,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'hashim',
  'Hashim',
  'HASHIM',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1980–1984). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1980–1984). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'us_artist',
  ARRAY['Hip Hop', 'Breaks'],
  '1980–1984',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  132,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'herbie-hancock',
  'Herbie Hancock',
  'HERBIE HANCOCK',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1980–1984). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1980–1984). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'us_artist',
  ARRAY['Hip Hop', 'Breaks'],
  '1980–1984',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  131,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'hybrid',
  'Hybrid',
  'HYBRID',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1995–1999). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1995–1999). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1995–1999',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  182,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'hyper',
  'Hyper',
  'HYPER',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2000–2004). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2000–2004). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '2000–2004',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  185,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'james-brown',
  'James Brown',
  'JAMES BROWN',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1970–1974). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1970–1974). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1970–1974',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  102,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'jimmy-castor-bunch',
  'Jimmy Castor Bunch',
  'JIMMY CASTOR BUNCH',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1970–1974). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1970–1974). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1970–1974',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  106,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'jonzun-crew',
  'Jonzun Crew',
  'JONZUN CREW',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1980–1984). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1980–1984). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'us_artist',
  ARRAY['Hip Hop', 'Breaks'],
  '1980–1984',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  138,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'keith-mackenzie',
  'Keith Mackenzie',
  'KEITH MACKENZIE',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2010–2014). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2010–2014). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2010–2014',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  205,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'kool-the-gang',
  'Kool & The Gang',
  'KOOL & THE GANG',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1970–1974). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1970–1974). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1970–1974',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  113,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'kurtis-blow',
  'Kurtis Blow',
  'KURTIS BLOW',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1980–1984). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1980–1984). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'us_artist',
  ARRAY['Hip Hop', 'Breaks'],
  '1980–1984',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  139,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'left-right',
  'Left/Right',
  'LEFT/RIGHT',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2015–2019). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2015–2019). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2015–2019',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  210,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'liquid-liquid',
  'Liquid Liquid',
  'LIQUID LIQUID',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1975–1979). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1975–1979). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1975–1979',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  127,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'lovebug-starski',
  'Lovebug Starski',
  'LOVEBUG STARSKI',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1975–1979). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1975–1979). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1975–1979',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  119,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'ltj-bukem',
  'LTJ Bukem',
  'LTJ BUKEM',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1990–1994). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1990–1994). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1990–1994',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  167,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'lyn-collins',
  'Lyn Collins',
  'LYN COLLINS',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1970–1974). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1970–1974). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1970–1974',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  105,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'malcolm-mclaren',
  'Malcolm McLaren',
  'MALCOLM MCLAREN',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1980–1984). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1980–1984). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '1980–1984',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  136,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'mandrill',
  'Mandrill',
  'MANDRILL',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1975–1979). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1975–1979). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1975–1979',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  126,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'mantronix',
  'Mantronix',
  'MANTRONIX',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1980–1984). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1980–1984). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'us_artist',
  ARRAY['Hip Hop', 'Breaks'],
  '1980–1984',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  135,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'marten-h-rger',
  'Marten Hørger',
  'MARTEN HØRGER',
  'DE',
  'Key name in the Optimal Breaks artist timeline (2005–2009). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2005–2009). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '2005–2009',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  197,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'meat-beat-manifesto',
  'Meat Beat Manifesto',
  'MEAT BEAT MANIFESTO',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1985–1989). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1985–1989). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1985–1989',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  149,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'meat-katie',
  'Meat Katie',
  'MEAT KATIE',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1995–1999). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1995–1999). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1995–1999',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  180,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'mfsb',
  'MFSB',
  'MFSB',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1970–1974). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1970–1974). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1970–1974',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  108,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'n-joi',
  'N-Joi',
  'N-JOI',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1990–1994). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1990–1994). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1990–1994',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  162,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'n-w-a',
  'N.W.A.',
  'N.W.A.',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1985–1989). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1985–1989). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'us_artist',
  ARRAY['Hip Hop', 'Breaks'],
  '1985–1989',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  153,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'newcleus',
  'Newcleus',
  'NEWCLEUS',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1980–1984). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1980–1984). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'us_artist',
  ARRAY['Hip Hop', 'Breaks'],
  '1980–1984',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  133,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'olivia-rose',
  'Olivia Rose',
  'OLIVIA ROSE',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2025 →). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2025 →). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2025 →',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  218,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'ondamike',
  'Ondamike',
  'ONDAMIKE',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2015–2019). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2015–2019). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2015–2019',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  211,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'parliament',
  'Parliament',
  'PARLIAMENT',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1975–1979). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1975–1979). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1975–1979',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  122,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'perfect-kombo',
  'Perfect Kombo',
  'PERFECT KOMBO',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2020–2024). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2020–2024). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2020–2024',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  213,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'propellerheads',
  'Propellerheads',
  'PROPELLERHEADS',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1995–1999). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1995–1999). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1995–1999',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  178,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'rasco',
  'Rasco',
  'RASCO',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2015–2019). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2015–2019). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2015–2019',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  209,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'rebel-mc-congo-natty',
  'Rebel MC / Congo Natty',
  'REBEL MC / CONGO NATTY',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1990–1994). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1990–1994). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1990–1994',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  168,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'rennie-pilgrem',
  'Rennie Pilgrem',
  'RENNIE PILGREM',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1995–1999). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1995–1999). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1995–1999',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  177,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'run-d-m-c',
  'Run-D.M.C.',
  'RUN-D.M.C.',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1980–1984). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1980–1984). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'us_artist',
  ARRAY['Hip Hop', 'Breaks'],
  '1980–1984',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  130,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  's-express',
  'S’Express',
  'S’EXPRESS',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1985–1989). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1985–1989). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1985–1989',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  145,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'shade-k',
  'Shade K',
  'SHADE K',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2015–2019). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2015–2019). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2015–2019',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  208,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'sl2',
  'SL2',
  'SL2',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1990–1994). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1990–1994). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1990–1994',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  159,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'sly-the-family-stone',
  'Sly & The Family Stone',
  'SLY & THE FAMILY STONE',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1970–1974). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1970–1974). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1970–1974',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  107,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'slynk',
  'Slynk',
  'SLYNK',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2010–2014). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2010–2014). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2010–2014',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  200,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'the-beastie-boys',
  'The Beastie Boys',
  'THE BEASTIE BOYS',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1980–1984). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1980–1984). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'us_artist',
  ARRAY['Hip Hop', 'Breaks'],
  '1980–1984',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  142,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'the-breakfastaz',
  'The Breakfastaz',
  'THE BREAKFASTAZ',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2000–2004). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2000–2004). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '2000–2004',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  186,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'the-crystal-method',
  'The Crystal Method',
  'THE CRYSTAL METHOD',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1995–1999). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1995–1999). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1995–1999',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  172,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'the-incredible-bongo-band',
  'The Incredible Bongo Band',
  'THE INCREDIBLE BONGO BAND',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1970–1974). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1970–1974). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1970–1974',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  103,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'the-isley-brothers',
  'The Isley Brothers',
  'THE ISLEY BROTHERS',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1970–1974). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1970–1974). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1970–1974',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  114,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'the-klf',
  'The KLF',
  'THE KLF',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1985–1989). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1985–1989). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1985–1989',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  156,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'the-ragga-twins',
  'The Ragga Twins',
  'THE RAGGA TWINS',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1990–1994). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1990–1994). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1990–1994',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  164,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'the-winstons',
  'The Winstons',
  'THE WINSTONS',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1970–1974). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1970–1974). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1970–1974',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  104,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'tipper',
  'Tipper',
  'TIPPER',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1995–1999). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1995–1999). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'uk_legend',
  ARRAY['Breakbeat', 'Electronic'],
  '1995–1999',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  174,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'tyree',
  'Tyree',
  'TYREE',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1985–1989). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1985–1989). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'us_artist',
  ARRAY['Hip Hop', 'Breaks'],
  '1985–1989',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  155,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'utfo',
  'UTFO',
  'UTFO',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1980–1984). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1980–1984). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'us_artist',
  ARRAY['Hip Hop', 'Breaks'],
  '1980–1984',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  140,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'war',
  'War',
  'WAR',
  'UK',
  'Key name in the Optimal Breaks artist timeline (1975–1979). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1975–1979). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'pioneer',
  ARRAY['Funk', 'Soul', 'Breaks'],
  '1975–1979',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  125,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'wbbl',
  'WBBL',
  'WBBL',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2010–2014). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2010–2014). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2010–2014',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  202,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'whodini',
  'Whodini',
  'WHODINI',
  'USA',
  'Key name in the Optimal Breaks artist timeline (1980–1984). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (1980–1984). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'us_artist',
  ARRAY['Hip Hop', 'Breaks'],
  '1980–1984',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  141,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
),
(
  'yokiz',
  'YOKIZ',
  'YOKIZ',
  'UK',
  'Key name in the Optimal Breaks artist timeline (2025 →). This profile is a starter entry linked from the /artists era map; editorial depth can grow over time.',
  'Nombre clave en la cronología de artistas de Optimal Breaks (2025 →). Esta ficha es una entrada inicial enlazada desde el mapa por lustros de /artistas; el texto puede ampliarse con el tiempo.',
  'current',
  ARRAY['Breakbeat', 'Electronic'],
  '2025 →',
  ARRAY[]::text[],
  ARRAY[]::text[],
  ARRAY[]::text[],
  NULL,
  '{}'::jsonb,
  false,
  217,
  NULL,
  ARRAY[]::text[],
  '[]'::jsonb,
  NULL
)
ON CONFLICT (slug) DO NOTHING;
